// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNHHLr6ljrxKQkUDac3LXhmoH_4rv68P4',
    appId: '1:855117246153:web:bfc2d829c53270e04de718',
    messagingSenderId: '855117246153',
    projectId: 'news-app-flutter-2fdfa',
    authDomain: 'news-app-flutter-2fdfa.firebaseapp.com',
    storageBucket: 'news-app-flutter-2fdfa.firebasestorage.app',
    measurementId: 'G-0GYZPTL5W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcGDfhzsVG71rLCyTGyKob8CQlD170Nk8',
    appId: '1:855117246153:android:3c80f5a4643229964de718',
    messagingSenderId: '855117246153',
    projectId: 'news-app-flutter-2fdfa',
    storageBucket: 'news-app-flutter-2fdfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjq-ZhHPQ2AyBm_BoHhRHRcIV9QrFjfdM',
    appId: '1:855117246153:ios:4653176b7704e27c4de718',
    messagingSenderId: '855117246153',
    projectId: 'news-app-flutter-2fdfa',
    storageBucket: 'news-app-flutter-2fdfa.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjq-ZhHPQ2AyBm_BoHhRHRcIV9QrFjfdM',
    appId: '1:855117246153:ios:4653176b7704e27c4de718',
    messagingSenderId: '855117246153',
    projectId: 'news-app-flutter-2fdfa',
    storageBucket: 'news-app-flutter-2fdfa.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNHHLr6ljrxKQkUDac3LXhmoH_4rv68P4',
    appId: '1:855117246153:web:5170935e20be26c44de718',
    messagingSenderId: '855117246153',
    projectId: 'news-app-flutter-2fdfa',
    authDomain: 'news-app-flutter-2fdfa.firebaseapp.com',
    storageBucket: 'news-app-flutter-2fdfa.firebasestorage.app',
    measurementId: 'G-DRGSV69YMN',
  );
}
